apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: gitlab-demo
  title: GitLab DEMO 5
  description: Scaffolder GitLab Demo
spec:
  owner: backstage/techdocs-core
  type: service

  parameters:
    - title: Fill in service info
      required:
        - name
        - group
        - repo
      properties:
        name:
          title: Project Name
          type: string
          description: Tên project (hiển thị)
          ui:autofocus: true

        group:
          title: GitLab Group Name
          type: string
          description: Tên namespace/group trong GitLab mà bạn có quyền

        repo:
          title: Repository Name
          type: string
          description: Tên repo sẽ được tạo trong group

  steps:
    - id: fetch
      name: Fetch local source from ./code
      action: fetch:template
      input:
        url: ./code
        targetPath: ./template-source
        values:
          component_id: ${{ parameters.name }}
          description: "Generated from GitLab template"
          destination:
            owner: ${{ parameters.group }}
            repo: ${{ parameters.repo }}
          owner: backstage/techdocs-core

    - id: publish
      name: Publish to GitLab
      action: publish:gitlab
      input:
        description: This is ${{ parameters.name }}
        repoUrl: gitlab.com?owner=${{ parameters.group }}&repo=${{ parameters.repo }}
        sourcePath: ./template-source
        defaultBranch: develop-release

    - id: create-repository
      name: Create Gitlab Repository Token
      action: gitlab:projectDeployToken:create
      input:
        repoUrl: gitlab.com?owner=${{ parameters.group }}&repo=${{ parameters.repo }}
        projectId: "${{ steps['publish'].output.projectId }}"
        name: ${{ parameters.name }}-secret
        username: ${{ parameters.name }}-secret
        scopes: ['read_registry']

    - id: register
      name: Register to Backstage
      action: catalog:file
      input:
        repoContentsUrl: gitlab.com?owner=${{ parameters.group }}&repo=${{ parameters.repo }}
        catalogFile: 'catalog-info.yaml'

  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
