apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-react-app-gitlab
  title: Create React App on GitLab 
  description: Scaffold and publish a GitLab project
  tags:
    - react
    - gitlab
spec:
  owner: web@example.com
  type: website

  parameters:
    - title: Provide some simple information
      required:
        - component_id
        - owner
        - repoUrl
      properties:
        component_id:
          title: Name
          type: string
          description: Unique name of the component
          ui:field: EntityNamePicker
        description:
          title: Description
          type: string
          description: Help others understand what this website is for.
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - gitlab.com

  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./code
        values:
          component_id: ${{ parameters.component_id }}
          description: ${{ parameters.description }}
          destination: ${{ parameters.repoUrl | parseRepoUrl }}
          owner: ${{ parameters.owner }}

    - id: publish
      name: Publish to GitLab
      action: publish:gitlab
      input:
        allowedHosts: ['gitlab.com']
        description: This is ${{ parameters.component_id }}
        repoUrl: ${{ parameters.repoUrl }}

    - id: create-kubernetes-namespace
      name: Create Kubernetes Namespace
      action: kubernetes:create-namespace
      input:
        namespace: ${{ parameters.component_id }}-ns
        clusterRef: k8s-local-demo-env
        url: https://rancher-local.jitsinnovationlabs.com/k8s/clusters/c-gt2kd
        token: kubeconfig-u-rsg92v7ttc:zdwl4bzkzwxggn6tslzl7j8bv54t9cvp7crmc8sztjlns9xxqpdt6p
        skipTLSVerify: true
        caData: >-
          LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ2VENDQ\
      VdPZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQkdNUnd3R2dZRFZRUUtFeE5rZVc1aGJXbGoKY\
      kdsemRHVnVaWEl0YjNKbk1TWXdKQVlEVlFRRERCMWtlVzVoYldsamJHbHpkR1Z1WlhJdFkyRkFNV\
      FkzT1RNNApPVGczT1RBZUZ3MHlNekF6TWpFd09URXhNVGxhRncwek16QXpNVGd3T1RFeE1UbGFNR\
      Vl4SERBYUJnTlZCQW9UCkUyUjVibUZ0YVdOc2FYTjBaVzVsY2kxdmNtY3hKakFrQmdOVkJBTU1IV\
      1I1Ym1GdGFXTnNhWE4wWlc1bGNpMWoKWVVBeE5qYzVNemc1T0RjNU1Ga3dFd1lIS29aSXpqMENBU\
      VlJS29aSXpqMERBUWNEUWdBRUZCOGtDOHQxbkgvRwpVZDE5aW5zYTV3N1NveGtiK2Z0MlBhSmtZb\
      XpZaFdaTVFkRmZhR2VYampYWlRKVjlFWlZhRDRON0Z6L0hwSFdrCkx3dFc2NmIwUjZOQ01FQXdEZ\
      1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWUQKVlIwT0JCWUVGT\
      3duYjVPMVkvZkNocWZSZ1pBbEUvY1ZpOEgxTUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSVFDagpze\
      UJYT3ZjdlFCc1FIbjRXSCtIWlQ4UWZiT21zRVpkUFRMV29QU0ZOakFJZ0ZaQ1l4aWdiRGxUa2Rqd\
      0xjTjU2CklrdCtVOHZ1UGhEa04xZWo2citEMXd3PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
        labels: |
          app.io/type=ns;
          app.io/managed-by=org;
          
    - id: register
      name: Register to Backstage
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
