apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: gitlab-demo
  title: GitLab DEMO 1
  description: Scaffolder GitLab Demo
spec:
  owner: backstage/techdocs-core
  type: service

  parameters:
    - title: Fill in service info
      required:
        - name
        - group
        - repo
      properties:
        name:
          title: Project Name
          type: string
          description: Tên project (hiển thị)
          ui:autofocus: true

        group:
          title: GitLab Group Name
          type: string
          description: Tên namespace/group trong GitLab mà bạn có quyền

        repo:
          title: Repository Name
          type: string
          description: Tên repo sẽ được tạo trong group

  steps:
    - id: fetch
      name: Fetch GitLab Source Archive
      action: fetch:plain
      input:
        url: https://gitlab.com/thanghumg113-group/react-app-simple/-/archive/develop-release/react-app-simple-develop-release.zip
        targetPath: ./template-source
        extract: true
  
    - id: copy
      name: Copy extracted content
      action: backstage:execute
      input:
        command: bash
        args:
          - -c
          - |
            folder=$(find ./template-source -maxdepth 1 -type d -name "react-app-simple-develop-release*" | head -n1)
            mkdir -p ./template-app
            cp -r "$folder"/* ./template-app/
  
    - id: publish
      name: Publish to GitLab
      action: publish:gitlab
      input:
        description: This is ${{ parameters.name }}
        repoUrl: gitlab.com?owner=${{ parameters.group }}&repo=${{ parameters.repo }}
        sourcePath: ./template-app
        defaultBranch: develop-release

    - id: create-repository
      name: Create Gitlab Deploy Token
      action: gitlab:projectDeployToken:create
      input:
        repoUrl: gitlab.com?owner=${{ parameters.group }}&repo=${{ parameters.repo }}
        projectId: "${{ steps['publish'].output.projectId }}"
        name: ${{ parameters.name }}-secret
        username: ${{ parameters.name }}-secret
        scopes: ['read_registry']

    - id: register
      name: Register to Backstage
      action: catalog:register
      input:
        catalogInfoUrl: https://raw.githubusercontent.com/thangjits/software-templates/refs/heads/main/react-gitlab-template-local/template/catalog-info.yaml

  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
