apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: gitlab-demo
  title: Gitlab DEMO 2
  description: Scaffolder Gitlab Demo
spec:
  owner: backstage/techdocs-core
  type: service

  parameters:
    - title: Fill in service info
      required:
        - name
        - group
        - repo
      properties:
        name:
          title: Project Name
          type: string
          description: Tên project (hiển thị)
          ui:autofocus: true

        group:
          title: GitLab Group Name
          type: string
          description: Tên namespace/group trong GitLab mà bạn có quyền

        repo:
          title: Repository Name
          type: string
          description: Tên repo sẽ được tạo trong group

  steps:
    - id: fetch
      name: Fetch local source
      action: fetch:plain
      input:
        url: ./code

    - id: ensure-group
      name: Ensure GitLab group exists
      action: gitlab:group:ensureExists
      input:
        repoUrl: gitlab.com?owner=${{ parameters.group }}
        path: ${{ parameters.group }}

    - id: check-repo
      name: Check GitLab repository exists
      action: gitlab:repository:check
      input:
        repoUrl: gitlab.com?owner=${{ parameters.group }}&repo=${{ parameters.repo }}

    - id: publish
      name: Publish
      action: publish:gitlab
      input:
        description: This is ${{ parameters.name }}
        repoUrl: gitlab.com?owner=${{ parameters.group }}&repo=${{ parameters.repo }}
        sourcePath: pimcore
        defaultBranch: main

    - id: gitlab-deploy-token
      name: Create Deploy Token
      action: gitlab:projectDeployToken:create
      input:
        repoUrl: gitlab.com?owner=${{ parameters.group }}&repo=${{ parameters.repo }}
        projectId: "${{ steps['publish'].output.projectId }}"
        name: ${{ parameters.name }}-secret
        username: ${{ parameters.name }}-secret
        scopes: ['read_registry']

    - id: gitlab-project-variable
      name: Gitlab Project Variable
      action: gitlab:projectVariable:create
      input:
        repoUrl: gitlab.com?owner=${{ parameters.group }}&repo=${{ parameters.repo }}
        projectId: "${{ steps['publish'].output.projectId }}"
        key: 'VARIABLE_NAME'
        value: "${{ steps['gitlab-deploy-token'].output.token }}"
        variableType: 'env_var'
        masked: true
        variableProtected: false
        raw: false
        environmentScope: '*'

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
