apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: gitlab-demo
  title: GitLab DEMO 4
  description: Scaffold and publish a GitLab project
spec:
  owner: demo@jits.com
  type: website

  parameters:
    - title: Provide some simple information
      required:
        - component_id
        - owner
        - repo
      properties:
        component_id:
          title: Name
          type: string
          description: Unique name of the component
          ui:field: EntityNamePicker

        description:
          title: Description
          type: string
          description: Help others understand what this website is for.

        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group

        repo:
          type: string
          title: GitLab repository name

  steps:
    - id: template
      name: Fetch local template
      action: fetch:template
      input:
        url: ./code
        values:
          component_id: ${{ parameters.component_id }}
          description: ${{ parameters.description }}
          destination: ${{ { owner: parameters.owner, repo: parameters.repo } }}
          owner: ${{ parameters.owner }}
          repo: ${{ parameters.repo }}

    - id: publish
      name: Publish to GitLab
      action: publish:gitlab
      input:
        allowedHosts: ['gitlab.com']
        description: GitLab project for ${{ parameters.component_id }}
        repoUrl: gitlab.com?owner=${{ parameters.owner }}&repo=${{ parameters.repo }}
        sourcePath: .
        defaultBranch: develop-release

    - id: create-repository
      name: Create GitLab Deploy Token
      action: gitlab:projectDeployToken:create
      input:
        repoUrl: gitlab.com?owner=${{ parameters.owner }}&repo=${{ parameters.repo }}
        projectId: "${{ steps['publish'].output.projectId }}"
        name: ${{ parameters.component_id }}-secret
        username: ${{ parameters.component_id }}-secret
        scopes: ['read_registry']

    - id: register
      name: Register to Backstage
      action: catalog:register
      input:
        catalogInfoUrl: https://gitlab.com/${{ parameters.owner }}/${{ parameters.repo }}/-/blob/develop-release/catalog-info.yaml

  output:
    links:
      - title: Repository
        url: https://gitlab.com/${{ parameters.owner }}/${{ parameters.repo }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
