apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.component_id }}
  description: ${{ values.description }}
  annotations:
    gitlab.com/project-slug: ${{ values.destination.owner + "/" + values.destination.repo }}
    backstage.io/techdocs-ref: dir:.
    backstage.io/ci-url: https://gitlab.com/${{ values.destination.owner }}/${{ values.destination.repo }}/-/pipelines
    backstage.io/kubernetes-id: ${{ values.component_id }}
spec:
  type: website
  lifecycle: experimental
  owner: ${{ values.owner }}
